### ISSUE TITLE
Data Cleaning

### ISSUE THREAD

**Issue by brigidangelini** [drc56/flight_club#24]
We need someone to go through the master flight club csv and perform data cleaning so we can load the complete dataset into the database. 

Main things to do: 
- ensure member names are consistent
- ensure brewery names are consistent
- for the rare duplicate beers, ensure the names are consistent
- ensure date formats are consistent, MM/DD/YYYY 
- ensure date ordering is consistent
- fill in missing data as needed

Verify that we have uploaded the cleaned completed csv to the repo to close this issue.

**Comment by drc0308** [comment]
Oh god we do don't we :(

**Comment by brigidangelini** [comment]
> Oh god we do don't we :(

we need an intern

**Comment by MariaRocco** [comment]
@drc56 I'm working on this - just need to add all the missing abv data - you will owe me a 4 pack upon merge NLT friday zoom :D
