### ISSUE TITLE
Migrate to Postgres

### ISSUE THREAD

**Issue by drc0308** [drc56/flight_club#26]
Sqlite is great for dev, but we'll need to use something better in deployment that doesn't just save in disk space. Everyone seems to like Postgres so let's do it.

**Comment by brigidangelini** [comment]
Will this include/should this include implementing database constraints? Is that implied? (I don't really know how to proper database design so I genuinely don't know lol) or is this captured somewhere else already? @drc56

**Comment by drc0308** [comment]
Probably a separate later on thing. For now it is just take exact same schema, move it, make sure nothing breaks. Also dockerize starting the db service. There are some simple constraints on it now, if we need more we can add them.

I also don't know much about database design as well though.
