### ISSUE TITLE
Add ABV to Beers, Session and User Profile

### ISSUE THREAD

**Issue by drc0308** [drc56/flight_club#7]
It's fun to know how boozy all the beers people drank were. The database models needs to be updated to that for each beer we store the ABV. I think this will require a few updates throughout the code base:

- Updates to the test csv files to include the ABV of the beers.
- Updates to the `Beer` model ins the `models/models.py` file to have an ABV field
- Updates to the `csv_load` in `dbhelper` and the session adding function. (Though that's a hot mess anyway...)

I think a cool thing also would be adding a display of average abv on a persons profile for the beers which they brought, and maybe an average abv on the sessions page as well.

**Comment by brigidangelini** [comment]
see pull request. 

Todo:
- display average ABVs on the session page, need to create method to calculate this in in `sessions/fc_sessions.py`

**Comment by drc0308** [comment]
@brigidangelini I like both of those ideas in your todos, if those were questions to me? Or just a statement of what still needs to happen.

**Comment by brigidangelini** [comment]
they're just statements of what still needs to happen  @drc56

**Comment by brigidangelini** [comment]
I think these all may be complete now. ABV added to session and user views, average abv added to sessions and user pages.

**Comment by brigidangelini** [comment]
Closing this since PR #12 was merged to master, please re-open if this is actually incomplete.
